# Harmony Jekyll theme general configurations 

# Base URL
baseurl: 

# Site live URL
url: http://evamvid.github.io

# Localhost 
#url: http://192.168.0.102:4000

# Harmony theme configuration. Please change accordingly.
harmony:
  name: Evam Sharma
  # Little description about your site
  description: A Developing Developer
  meta_description: Harmony is free responsive jekyll theme. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Evamvid Sharma
    email: evamvid@gmail.com
    url: http://evamvid.github.io

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-xxxx-x

  # Profile links, leave blank to ignore

footer-links:
  dribbble: 
  email: evamvid@gmail.com
  facebook: 
  flickr: 
  github: evamvid
  instagram: 
  linkedin: 
  pinterest: 
  rss: rss # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: evamvid
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  # Toggle disclaimer in footer
  show_disclaimer: true

# Conversion / Build settings 
markdown:    kramdown
highlighter: pygments # this is how you put pygments config in jekyll 2.0 instead of pygments: true

# Permalinks
permalink:        pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
